title: acm-tamusa
timezone: UTC
markdown: kramdown
collections:
  posts:
    output: true
title: acm-tamusa
url: https://Tr-Do.github.io        # no trailing slash
baseurl: /acm-tamusa                      # repo name, with leading slash
